# Generated by Django 4.0.2 on 2022-02-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('text', models.TextField(verbose_name='text')),
                ('author', models.TextField(verbose_name='author')),
            ],
        ),
    ]
