# Generated by Django 3.2.12 on 2022-02-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogparsing_sub_main', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='date',
            field=models.TextField(verbose_name='date'),
        ),
    ]
