# Generated by Django 3.2.12 on 2022-02-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogparsing_sub_main', '0002_alter_blognews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
