# Generated by Django 3.2.12 on 2022-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogparsing_sub_main', '0004_alter_blognews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='word_count',
            field=models.IntegerField(default=0, verbose_name='word_count'),
        ),
    ]
