# Generated by Django 3.2.12 on 2022-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogparsing_sub_main', '0005_blognews_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='top_words',
            field=models.TextField(default=None, verbose_name='top_words'),
            preserve_default=False,
        ),
    ]
